### ISSUE TITLE
Bootloader explanation

### ISSUE THREAD

**Issue by ghost** [m-kopka/rp2040-assembly-blink#1]
Can you explain a bit about the bootloader in the `.boot2` section and its function? Is it the code that handles the **BOOTSEL** button on the Pico?

Is it from the official SDK? I'd like to study the source and understand how the bootloader works and where it came from.

Thank you for posting this project, I've been looking for assembly-only development for Raspberry Pi Pico without the SDK.

**Comment by m-kopka** [comment]
Hi,

the RP2040's boot sequence is quite complicated because there is no non-volatile memory on-chip and we need to boot from an external flash chip.

**Stage 1 bootloader** is already present in ROM on the chip and it first puts core 1 to sleep and then checks the **BOOTSEL** button. if the button is pressed, it runs the USB boot code and shows up as an external drive on your computer. if the **BOOTSEL** button is not pressed, it reads first 256 bytes from the external flash chip and puts it to SRAM.

First 252 bytes contain the **stage 2 bootloader** and the remaining 4 bytes is CRC checksum of those 252 bytes.
The **stage 1 bootloader** checks the CRC to make sure its not reading garbage and jumps to the **stage 2 bootloader** if the CRC check passes.

The job of **stage 2 bootloader** is to configure the QSPI interface to efficiently communicate with the specific FLASH chip we are using so we can execute from it. After it's done it jumps to the entry point of your program.

The **stage 2 bootloader** i'm using is from the Pico SDK [boot stage2](https://github.com/raspberrypi/pico-sdk/tree/master/src/rp2_common/boot_stage2) (boot2_w25q080.S is for the W25Q16JV chip present on the Pico board).

I also experimented a bit with writing my own stage2. Basically, you:
- assemble it
- use arm-none-eabi-objdump to extract the raw bytes in hex
- add extra zeroes at the end, so its exactly 252 bytes
- use an [online tool](https://crccalc.com) to calculate the CRC32 checksum (the CRC-32/MPEG-2 variant)
- add the checksum at the end
- make sure it gets placed at the beginning of FLASH using a linker script

If the Pico shows up as an external drive even though you are not pressing the **BOOTSEL** button, it means you made a mistake and the CRC32 check didn't pass.

The boot sequence is described in much more detail in  [RP2040's datasheet](https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf) section 2.7 Boot sequence

**Comment by ghost** [comment]
Very helpful! Thank you so much!
